CREATE TABLE IF NOT EXISTS `applicant` (
    `ID` int NOT NULL AUTO_INCREMENT,
    `transaction` varchar(200) NOT NULL,
    `classification` varchar(200) NOT NULL,
    `use` varchar(200) NOT NULL,
    `surname` varchar(200) NOT NULL,
    `firstName` varchar(200) NOT NULL,
    `middleName` varchar(200),
    `maidenName` varchar(200),
    `sex` varchar(200),
    `birthplace` varchar(200),
    `birthdate` date,
    `nationality` varchar(200),
    `street` varchar(200),
    `city` varchar(200),
    `email` varchar(200),
    `countryCode` int(3),
    `areaCode` int(3),
    `suffix` int(4),
    `altStreet` varchar(200),
    `altCity` varchar(200),
    `altEmail` varchar(200),
    `altCountryCode` int(3),
    `altAreaCode` int(3),
    `altSuffix` int(4),
    `dpHolderPresent` varchar(200),
    `dpHolderPrevious` varchar(200),
    `dpNumber` int(200),
    `issueDate` date,
    `vehicleClass` varchar(200),
    `foreignDP` varchar(200),
    `particulars` text(65000),
    `disqualifiedStatus` varchar(200),
    `disqualificationParticulars` text(65000),
    `physique` varchar(200),
    `fullName` varchar(200),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;